# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kq3rx4v6m2qUY-ilV4PH9ZLi7U9BIvQb
"""

!pip -q install -U \
    groq \
    tavily-python \
    langgraph \
    langchain-core \
    sentence-transformers \
    faiss-cpu \
    pypdf



import os

os.environ["GROQ_API_KEY"] = GROQ_API_KEY
os.environ["TAVILY_API_KEY"] = TAVILY_API_KEY


# Library
import os
import json
import re
import sqlite3
from pathlib import Path
from typing import TypedDict, Annotated

from groq import Groq
from tavily import TavilyClient

from langgraph.graph import StateGraph, START, END
from langchain_core.tools import tool

import faiss
import numpy as np

from sentence_transformers import SentenceTransformer
from pypdf import PdfReader


GROQ_MODEL = "openai/gpt-oss-20b"

groq_client = Groq(
    api_key=os.environ["GROQ_API_KEY"]
)

tavily_client = TavilyClient(
    api_key=os.environ["TAVILY_API_KEY"]
)
# this is deamo database apply me real database and thier arciture next to this code antigravity
DB_PATH = "/content/company.db"

DOCS_PATH = "/content/company-documents"

# print("Groq:", GROQ_MODEL)
# print("DB:", DB_PATH)
# print("Docs:", DOCS_PATH)



def get_database_schema(db_path=DB_PATH):
    conn = sqlite3.connect(db_path)

    tables = conn.execute("""
        SELECT name
        FROM sqlite_master
        WHERE type='table'
        AND name NOT LIKE 'sqlite_%'
        ORDER BY name
    """).fetchall()

    schema = {}

    for (table_name,) in tables:

        columns = conn.execute(
            f'PRAGMA table_info("{table_name}")'
        ).fetchall()

        schema[table_name] = [
            {
                "name": col[1],
                "type": col[2],
                "primary_key": bool(col[5])
            }
            for col in columns
        ]

    conn.close()

    return schema


FORBIDDEN_SQL = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "CREATE",
    "REPLACE",
    "ATTACH",
    "DETACH",
    "VACUUM",
    "PRAGMA"
]


def validate_sql(sql: str):

    sql_clean = sql.strip().upper()

    if not (
        sql_clean.startswith("SELECT")
        or sql_clean.startswith("WITH")
    ):
        return False, "Only SELECT/WITH queries are allowed."

    for keyword in FORBIDDEN_SQL:
        pattern = rf"\b{keyword}\b"

        if re.search(pattern, sql_clean):
            return False, f"Forbidden SQL operation: {keyword}"

    return True, None




@tool
def database_query(sql: str) -> str:
    """
    Execute a READ-ONLY SQL query against the company SQLite database.

    The SQL must be SELECT or WITH only.

    Use this tool whenever the user asks for information
    that exists in the database.

    The query should retrieve the complete relevant record
    when identifying a customer.

    Examples:

    SELECT *
    FROM customers
    WHERE name LIKE '%Ahmed Mohamed%'

    SELECT *
    FROM orders
    WHERE customer_id = 1

    SELECT c.*, o.*
    FROM customers c
    LEFT JOIN orders o
        ON c.id = o.customer_id
    WHERE c.name LIKE '%Ahmed Mohamed%'
    """

    valid, error = validate_sql(sql)

    if not valid:
        return json.dumps({
            "success": False,
            "error": error
        })

    try:

        conn = sqlite3.connect(DB_PATH)

        conn.row_factory = sqlite3.Row

        cursor = conn.execute(sql)

        rows = cursor.fetchall()

        result = [
            dict(row)
            for row in rows
        ]

        conn.close()

        return json.dumps({
            "success": True,
            "row_count": len(result),
            "rows": result
        }, ensure_ascii=False)

    except Exception as e:

        return json.dumps({
            "success": False,
            "error": str(e)
        })



# we  will uplaod my documants pelase make or code conect to my docs and pdf not this i make it only for demo
from pathlib import Path

docs_dir = Path("/content/company-documents")
docs_dir.mkdir(parents=True, exist_ok=True)

demo_doc = """
COMPANY REFUND POLICY

Customers may request a refund within 14 days of purchase.

If a product is defective, the customer can request a replacement
or refund after the support team verifies the issue.

For delayed orders, the support team should inform the customer
about the delay and provide the latest expected delivery information.

A delayed order does not automatically qualify for a refund.
Refund eligibility must be evaluated according to the applicable
refund conditions.
"""

(docs_dir / "refund_policy.txt").write_text(
    demo_doc,
    encoding="utf-8"
)

# print("Created:", docs_dir / "refund_policy.txt")



def load_documents(folder):

    folder = Path(folder)

    documents = []

    for file_path in folder.rglob("*"):

        if not file_path.is_file():
            continue

        suffix = file_path.suffix.lower()

        try:

            # TXT
            if suffix == ".txt":

                text = file_path.read_text(
                    encoding="utf-8",
                    errors="ignore"
                )

                if text.strip():

                    documents.append({
                        "source": str(file_path),
                        "text": text
                    })

            # PDF
            elif suffix == ".pdf":

                reader = PdfReader(str(file_path))

                for page_number, page in enumerate(reader.pages):

                    text = page.extract_text() or ""

                    if text.strip():

                        documents.append({
                            "source": f"{file_path}#page={page_number+1}",
                            "text": text
                        })

        except Exception as e:

            print(
                f"Could not load {file_path}: {e}"
            )

    return documents




def chunk_text(
    text,
    chunk_size=800,
    overlap=120
):

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    if not text:
        return []

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunk = text[start:end]

        if chunk.strip():
            chunks.append(chunk)

        start = end - overlap

    return chunks



class SimpleRAG:

    def __init__(
        self,
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    ):

        print("Loading embedding model...")

        self.embedder = SentenceTransformer(
            model_name
        )

        self.index = None
        self.chunks = []

    def build(self, folder):

        documents = load_documents(folder)

        print(
            "Loaded documents/pages:",
            len(documents)
        )

        self.chunks = []

        for doc in documents:

            pieces = chunk_text(
                doc["text"]
            )

            for piece in pieces:

                self.chunks.append({
                    "text": piece,
                    "source": doc["source"]
                })

        print(
            "Created chunks:",
            len(self.chunks)
        )

        if not self.chunks:
            raise ValueError(
                "No documents found."
            )

        texts = [
            item["text"]
            for item in self.chunks
        ]

        embeddings = self.embedder.encode(
            texts,
            normalize_embeddings=True,
            show_progress_bar=True
        )

        embeddings = np.asarray(
            embeddings,
            dtype="float32"
        )

        dimension = embeddings.shape[1]

        self.index = faiss.IndexFlatIP(
            dimension
        )

        self.index.add(
            embeddings
        )

        print(
            "FAISS vectors:",
            self.index.ntotal
        )

    def search(
        self,
        question,
        k=4
    ):

        if self.index is None:
            return []

        query_embedding = self.embedder.encode(
            [question],
            normalize_embeddings=True
        )

        query_embedding = np.asarray(
            query_embedding,
            dtype="float32"
        )

        scores, indices = self.index.search(
            query_embedding,
            min(k, self.index.ntotal)
        )

        results = []

        for score, index in zip(
            scores[0],
            indices[0]
        ):

            if index < 0:
                continue

            item = self.chunks[index]

            results.append({
                "score": float(score),
                "source": item["source"],
                "text": item["text"]
            })

        return results



rag = SimpleRAG()
# make it path for my real documant please and apply for all documant maybe i have multiaaple documnt select best rag top use in it
rag.build(
    "/content/company-documents"
)



@tool
def rag_search_tool(question: str) -> str:
    """
    Search internal company documents, PDFs, policies,
    manuals and documentation.

    Use this for company knowledge and internal policies.
    """

    results = rag.search(
        question,
        k=4
    )

    if not results:

        return json.dumps({
            "success": False,
            "message": "No relevant documents found."
        })

    return json.dumps({
        "success": True,
        "results": results
    }, ensure_ascii=False)





@tool
def web_search_tool(query: str) -> str:
    """
    Search the public web using Tavily.

    Use this for current information,
    recent developments, latest news,
    current software versions and public information.
    """

    try:

        response = tavily_client.search(
            query=query,
            search_depth="basic",
            max_results=5
        )

        results = []

        for item in response.get(
            "results",
            []
        ):

            results.append({
                "title": item.get("title"),
                "url": item.get("url"),
                "content": item.get("content")
            })

        return json.dumps({
            "success": True,
            "results": results
        }, ensure_ascii=False)

    except Exception as e:

        return json.dumps({
            "success": False,
            "error": str(e)
        })



schema_text = json.dumps(
    schema,
    indent=2,
    ensure_ascii=False
)

print(schema_text)




# told him thje output must be clear dont write4 sql command in output please
SYSTEM_PROMPT = f"""
You are an intelligent Agentic AI assistant.

You have access to:

1. DATABASE
2. INTERNAL RAG
3. WEB SEARCH

Your job is to decide which tools are required.

==================================================
DATABASE SCHEMA
==================================================

{schema_text}

==================================================
DATABASE RULES
==================================================

The database contains real customer and business data.

You MUST generate SQL dynamically.

DO NOT use hard-coded customer IDs.

DO NOT assume:

customer_id = 1

DO NOT assume:

order_id = 1001

Instead, search the database.

==================================================
CUSTOMER QUESTIONS
==================================================

When the user mentions a customer by name:

FIRST identify the customer using SQL.

Example:

SELECT *
FROM customers
WHERE name LIKE '%Ahmed Mohamed%';

IMPORTANT:

When identifying a customer, retrieve the COMPLETE
customer record using:

SELECT *

This allows you to see:

- id
- name
- phone
- email
- status
- and any future fields

Do not retrieve only the field the user requested.

After finding the customer ID, use it to retrieve
related records from other tables.

Example:

SELECT *
FROM orders
WHERE customer_id = 1;

The ID must come from the previous database result.

==================================================
IMPORTANT
==================================================

The user may ask:

"What is Ahmed's phone?"

You should:

1. Find Ahmed.
2. Retrieve the full customer record.
3. Return only the phone.

The user may ask:

"What is Ahmed's email and phone?"

Retrieve the full record,
then return email and phone.

The user may ask:

"What did Ahmed order?"

Find Ahmed first,
then query the orders table using the returned customer ID.

The user may ask:

"What is Ahmed's order status?"

Find Ahmed,
then query the related orders.

==================================================
HYBRID QUESTIONS
==================================================

If the question requires customer data AND company policy:

Use DATABASE + RAG.

Example:

"Can Ahmed get a refund for his delayed laptop?"

You should:

1. Find Ahmed in the database.
2. Retrieve his complete customer record.
3. Retrieve his related order records.
4. Search RAG for the refund policy.
5. Compare the actual database facts with the policy.
6. Answer only what the evidence supports.

IMPORTANT:

Never conclude that something is allowed or eligible
unless the policy explicitly supports it.

For example:

"Delayed order"

does NOT automatically mean:

"Refund eligible."

==================================================
WEB
==================================================

Use web_search_tool for:

- latest information
- current information
- recent developments
- current software versions
- public internet information

Do NOT use web search for internal company policy.

==================================================
SQL SAFETY
==================================================

Only generate READ-ONLY SQL.

Allowed:

SELECT
WITH

Never generate:

INSERT
UPDATE
DELETE
DROP
ALTER
CREATE
REPLACE
ATTACH
DETACH
VACUUM

==================================================
NO HALLUCINATION
==================================================

Never invent database values.

Never invent customer information.

Never invent company policies.

Never invent eligibility.

If information is missing:

say exactly what is missing.

==================================================
FINAL ANSWERS
==================================================

Be concise.

For database questions:

return the requested information.

For hybrid questions:

explain:

1. Database facts
2. Policy facts
3. Conclusion

For web questions:

base the answer on retrieved search results.

Answer in the same language as the user.
"""




TOOLS = [
    database_query,
    rag_search_tool,
    web_search_tool
]






def tool_to_schema(tool):

    return {
        "type": "function",
        "function": {
            "name": tool.name,
            "description": tool.description,
            "parameters": tool.args_schema.model_json_schema()
        }
    }


TOOL_SCHEMAS = [
    tool_to_schema(tool)
    for tool in TOOLS
]

TOOL_MAP = {
    tool.name: tool
    for tool in TOOLS
}






def ask_agent(
    question,
    max_steps=6,
    verbose=True
):

    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": question
        }
    ]

    if verbose:

        print("=" * 70)
        print("USER")
        print("=" * 70)
        print(question)

        print()
        print("=" * 70)
        print("AGENT TRACE")
        print("=" * 70)

    for step in range(max_steps):

        response = groq_client.chat.completions.create(

            model=GROQ_MODEL,

            messages=messages,

            tools=TOOL_SCHEMAS,

            tool_choice="auto",

            temperature=0.1,

            max_completion_tokens=1200
        )

        message = response.choices[0].message

        tool_calls = message.tool_calls

        # -------------------------------
        # FINAL ANSWER
        # -------------------------------

        if not tool_calls:

            answer = message.content or ""

            if verbose:

                print()
                print("🤖 FINAL ANSWER:")
                print(answer)

            return answer

        # Add assistant tool-call message
        messages.append(
            message
        )

        # -------------------------------
        # EXECUTE TOOLS
        # -------------------------------

        for tool_call in tool_calls:

            tool_name = (
                tool_call.function.name
            )

            raw_arguments = (
                tool_call.function.arguments
            )

            try:

                arguments = json.loads(
                    raw_arguments
                )

            except Exception:

                arguments = {}

            if verbose:

                print()
                print(
                    f"🔧 TOOL → {tool_name}"
                )

                print(
                    "   Arguments:",
                    arguments
                )

            tool_function = TOOL_MAP.get(
                tool_name
            )

            if tool_function is None:

                result = json.dumps({
                    "error":
                    f"Unknown tool: {tool_name}"
                })

            else:

                try:

                    result = tool_function.invoke(
                        arguments
                    )

                except Exception as e:

                    result = json.dumps({
                        "error": str(e)
                    })

            if verbose:

                print(
                    "📦 TOOL RESULT →",
                    tool_name
                )

                # Don't dump huge documents
                preview = str(result)

                if len(preview) > 2000:
                    preview = preview[:2000] + "..."

                print(preview)

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": tool_name,
                "content": str(result)
            })

    return "The agent reached the maximum number of tool steps."